### ISSUE TITLE
Return challenge

### ISSUE THREAD

**Issue by htr-tech** [Datez-Kun/reverse-enginnering#7]
@Datez-Kun  Bro U gave me a challenge !! I have fulfilled it ! Now its a reverse Challenge !!

Decrypt The Files if you can 

[File One](https://anonfiles.com/h9T7z5Ifo4)

[File Two](http://gitlab.com/Sumarr-ID/auto_dec)

**Comment by Datez-Kun** [comment]
> @Datez-Kun Bro U gave me a challenge !! I have fulfilled it ! Now its a reverse Challenge !!
> 
> Decrypt The Files if you can
> 
> [File One](https://anonfiles.com/h9T7z5Ifo4)
> 
> [File Two](http://gitlab.com/Sumarr-ID/auto_dec)

You did not meet my challenge, because I already know, you only take files that have been decompiled in this repository 
https://raw.githubusercontent.com/Sazxt/reverse-engin/master/myfl/anti_decompile_out.py

the second file obviously can't be called a challenge, because the file doesn't belong to you🤣🤣 you're just curious about the source code but can't open it .... really embarrassing, covering up stupidity with a challenge
